# Generated by Django 4.2.1 on 2023-11-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDataModel',
            fields=[
                ('user_data_model_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('big_secret', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'user_data',
            },
        ),
    ]
