# Generated by Django 4.2.1 on 2023-10-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentModel',
            fields=[
                ('tournament_id', models.AutoField(primary_key=True, serialize=False)),
                ('tournament_name', models.CharField(max_length=50)),
                ('sport', models.CharField(max_length=30)),
                ('schedule', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tournaments',
            },
        ),
    ]
